# Generated by Django 3.1.3 on 2026-02-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(default='default_conversation', max_length=100, unique=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_weight', models.FloatField(help_text='Weight in kg')),
                ('birth_length', models.FloatField(help_text='Length in cm')),
                ('apgar_score', models.IntegerField()),
                ('complications', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('availability', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.babyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TelehealthAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('consultation_type', models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('chat', 'Text Chat')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telehealth_appointments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.healthcareprovider')),
            ],
        ),
        migrations.CreateModel(
            name='SOS_Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('personal', 'Personal Safety'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10, null=True)),
                ('role', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period', models.DateField()),
                ('due_date', models.DateField()),
                ('current_trimester', models.IntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')])),
                ('is_high_risk', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostpartumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('vaginal', 'Vaginal Birth'), ('c_section', 'C-Section')], max_length=20)),
                ('baby_weight', models.FloatField(help_text='Baby weight in kg')),
                ('complications', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PelvicFloorRehab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('muscle_strength', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('endurance_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('exercises_prescribed', models.TextField()),
                ('progress_notes', models.TextField(blank=True)),
                ('postpartum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.postpartumprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('trimester', models.IntegerField()),
                ('calories_needed', models.IntegerField()),
                ('protein_grams', models.IntegerField()),
                ('iron_mg', models.IntegerField()),
                ('calcium_mg', models.IntegerField()),
                ('folic_acid_mcg', models.IntegerField()),
                ('foods_recommended', models.TextField()),
                ('foods_to_avoid', models.TextField()),
                ('supplements', models.TextField()),
                ('pregnancy_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.pregnancyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadingdate', models.CharField(max_length=10, null=True)),
                ('reportfile', models.FileField(null=True, upload_to='')),
                ('filetype', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MEWS_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_saturation', models.IntegerField()),
                ('consciousness_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('urine_output', models.FloatField(help_text='Urine output in ml/hour')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('mood_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('anxiety_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('sleep_hours', models.FloatField()),
                ('appetite_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('notes', models.TextField(blank=True)),
                ('postpartum_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.postpartumprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('cycle_length', models.IntegerField(default=28)),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='Note any symptoms like cramps, headaches, etc.')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedate', models.CharField(max_length=10, null=True)),
                ('magazinesfile', models.FileField(null=True, upload_to='')),
                ('magazinestype', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('length', models.FloatField(help_text='Length in cm')),
                ('head_circumference', models.FloatField(help_text='Head circumference in cm')),
                ('milestones', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.babyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('completion_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('rehab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.pelvicfloorrehab')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='babyprofile',
            name='postpartum_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.postpartumprofile'),
        ),
        migrations.CreateModel(
            name='AISymptomChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('ai_analysis', models.TextField()),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('is_from_user', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='women.aiconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AIMedicationReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('reminder_time', models.TimeField(default='09:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIHealthInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('mental_health', 'Mental Health'), ('sleep', 'Sleep'), ('general', 'General')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
